name: Metrics
on:
  schedule:
    - cron: "0 0-23/1 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.ACCESS_TOKEN }}
          
          base: header
          
          plugin_isocalendar: yes
          
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used                            
                   
          config_order: base.header, isocalendar, languages, activity, reactions
          
